#!/bin/bash

function info {
    printf "\033[0;36m===> \033[0;33m${1}\033[0m\n"
}

service php5-fpm restart

rm -f /var/run/apache2/apache2.pid
service apache2 restart

PRESTASHOP_PATH=/var/www/html

info "Sleep 10s, waiting for mysql"
sleep 10

info "Install PrestaShop"
php $PRESTASHOP_PATH/install/index_cli.php --domain=$DOMAIN --db_server=$DB_HOST --db_name=$MYSQL_DATABASE \
	--db_user=$MYSQL_USER --db_password=$MYSQL_PASSWORD 

mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e \
	"UPDATE ps_configuration SET value = \"$DOMAIN\" WHERE name LIKE \"PS_SHOP_DOMAIN%\";"
mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e \
	"UPDATE ps_shop_url SET domain = \"$DOMAIN\", domain_ssl = \"$DOMAIN\";"

rm -rf $PRESTASHOP_PATH/install

chmod -R 777 $PRESTASHOP_PATH

while true; do
echo "Everything fine"
sleep 3600
done
